/// Flutter icons PauseDefiIcon
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PauseDefiIcon
///      fonts:
///       - asset: fonts/PauseDefiIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class PauseDefiIcon {
  PauseDefiIcon._();

  static const _kFontFam = 'PauseDefiIcon';
  static const String? _kFontPkg = null;

  static const IconData target = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ranking = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData medal = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
